version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: User
      POSTGRES_PASSWORD: Password
      POSTGRES_DB: Shortener
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres_data:
